version: '3.9'

services:
  app:
    build: .
    hostname: order-server
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    volumes:
      - ./docker.env:/app/.env

  mongodb:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 5s

volumes:
  mongodata:
